#!/usr/bin/env bash
# Build an Apple Silicon Spek.app from an upstream source tree and zip it.
# Spek itself is copyright Alexander Kojevnikov and contributors (GPL-3.0).
# This script only compiles and bundles that source.

set -euo pipefail

LANGUAGES="bs ca cs da de el eo es fi fr gl he hr hu id it ja ko lv nb nl nn pl pt_BR ru sk sr@latin sv th tr uk vi zh_CN zh_TW"

usage() {
    echo "Usage: $0 <spek-source-dir>" >&2
    exit 1
}

if [ "${1:-}" = "" ]; then
    usage
fi

SPEK_SRC="$(cd "$1" && pwd)"
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT_DIR="$ROOT/dist"

if [ "$(uname -m)" != "arm64" ]; then
    echo "This script builds Apple Silicon only (uname -m is $(uname -m))" >&2
    exit 1
fi

if [ "$(uname -s)" != "Darwin" ]; then
    echo "This script must run on macOS" >&2
    exit 1
fi

if ! command -v brew >/dev/null; then
    echo "Homebrew is required to bundle Spek." >&2
    exit 1
fi

if [ ! -x "$SPEK_SRC/autogen.sh" ]; then
    echo "Not a Spek source tree: $SPEK_SRC" >&2
    exit 1
fi

HOMEBREW_PREFIX="$(brew --prefix)"
GETTEXT_PREFIX="$(brew --prefix gettext)"
WX_PREFIX="$(brew --prefix wxwidgets)"

export PATH="$GETTEXT_PREFIX/bin:$PATH"

shopt -s nullglob
extra_aclocal=()
if [ -d "$GETTEXT_PREFIX/share/aclocal" ]; then
    extra_aclocal+=("$GETTEXT_PREFIX/share/aclocal")
fi
if [ -d "$GETTEXT_PREFIX/share/gettext/m4" ]; then
    extra_aclocal+=("$GETTEXT_PREFIX/share/gettext/m4")
fi
if [ -d "$WX_PREFIX/share/aclocal" ]; then
    extra_aclocal+=("$WX_PREFIX/share/aclocal")
fi
for d in "$WX_PREFIX"/share/wx/*/aclocal; do
    extra_aclocal+=("$d")
done
if [ "${#extra_aclocal[@]}" -gt 0 ]; then
    extra="$(IFS=:; echo "${extra_aclocal[*]}")"
    export ACLOCAL_PATH="$extra${ACLOCAL_PATH:+:$ACLOCAL_PATH}"
fi
shopt -u nullglob

# Homebrew bottles live under $(brew --prefix), which is not on Apple clang's
# default include path. Upstream GUI objects include libavutil/mem.h via
# spek-fft.h without AVUTIL_CFLAGS; Homebrew's formula injects these flags.
export PKG_CONFIG_PATH="$HOMEBREW_PREFIX/lib/pkgconfig${PKG_CONFIG_PATH:+:$PKG_CONFIG_PATH}"
export CPPFLAGS="-I$HOMEBREW_PREFIX/include -I$GETTEXT_PREFIX/include ${CPPFLAGS:-}"
export LDFLAGS="-L$HOMEBREW_PREFIX/lib -L$GETTEXT_PREFIX/lib -Wl,-headerpad_max_install_names ${LDFLAGS:-}"

cd "$SPEK_SRC"
rm -f src/spek

JOBS="$(sysctl -n hw.ncpu 2>/dev/null || echo 8)"
# Skip make check: upstream 0.8.5 fixtures fail against Homebrew FFmpeg 8
# (mp3 duration, AAC sample count, FFT silence). Packaging does not need them.
./autogen.sh --disable-silent-rules --disable-valgrind
make -j"$JOBS"

if [ ! -f config.h ]; then
    echo "config.h was not generated" >&2
    exit 1
fi
VERSION="$(sed -n 's/^#define PACKAGE_VERSION "\(.*\)"/\1/p' config.h)"
if [ -z "$VERSION" ]; then
    echo "Could not determine PACKAGE_VERSION from config.h" >&2
    exit 1
fi

OSX_DIR="$SPEK_SRC/dist/osx"
if [ ! -f "$OSX_DIR/Info.plist" ]; then
    echo "dist/osx/Info.plist was not generated by configure" >&2
    exit 1
fi

APP="$OUT_DIR/Spek.app"
rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Frameworks" "$APP/Contents/Resources"

if [ -f "$SPEK_SRC/src/.libs/spek" ]; then
    cp "$SPEK_SRC/src/.libs/spek" "$APP/Contents/MacOS/Spek"
else
    cp "$SPEK_SRC/src/spek" "$APP/Contents/MacOS/Spek"
fi
chmod +x "$APP/Contents/MacOS/Spek"
if ! file "$APP/Contents/MacOS/Spek" | grep -q 'Mach-O'; then
    echo "src/spek is not a Mach-O binary" >&2
    file "$APP/Contents/MacOS/Spek" >&2
    exit 1
fi

cp "$OSX_DIR/Info.plist" "$APP/Contents/"
cp "$OSX_DIR/Spek.icns" "$APP/Contents/Resources/"
cp "$OSX_DIR/"*.png "$APP/Contents/Resources/"
# Upstream file names vary by tag (v0.8.5 has LICENCE.md, no CREDITS.md).
copy_if_present() {
    local src="$1"
    if [ -f "$src" ]; then
        cp "$src" "$APP/Contents/Resources/"
    fi
}
copy_if_present "$SPEK_SRC/CREDITS.md"
copy_if_present "$SPEK_SRC/LICENSE"
copy_if_present "$SPEK_SRC/LICENCE.md"
copy_if_present "$SPEK_SRC/README.md"
if [ -d "$SPEK_SRC/lic" ]; then
    mkdir "$APP/Contents/Resources/lic"
    cp "$SPEK_SRC/lic/"* "$APP/Contents/Resources/lic/"
fi

for lang in $LANGUAGES; do
    mkdir -p "$APP/Contents/Resources/${lang}.lproj"
    cp -v "$SPEK_SRC/po/${lang}.gmo" "$APP/Contents/Resources/${lang}.lproj/spek.mo"
    copied_wx=0
    shopt -s nullglob
    for mo in "$HOMEBREW_PREFIX/share/locale/$lang/LC_MESSAGES"/wxstd-*.mo \
              "$HOMEBREW_PREFIX/share/locale/$lang/LC_MESSAGES/wxstd.mo"; do
        cp -v "$mo" "$APP/Contents/Resources/${lang}.lproj/"
        copied_wx=1
    done
    shopt -u nullglob
    if [ "$copied_wx" -eq 0 ]; then
        echo "No WX translation for $lang"
    fi
done
mkdir -p "$APP/Contents/Resources/en.lproj"

# Resolve a dependent library path from otool(1) against the original file.
resolve_dep() {
    local dep="$1"
    local origin="$2"
    local origin_dir
    origin_dir="$(dirname "$origin")"
    case "$dep" in
        @executable_path/*)
            return 1
            ;;
        @loader_path/*)
            local loader_candidate="$origin_dir/${dep#@loader_path/}"
            if [ -f "$loader_candidate" ]; then
                echo "$loader_candidate"
                return 0
            fi
            loader_candidate="$HOMEBREW_PREFIX/lib/$(basename "$dep")"
            if [ -f "$loader_candidate" ]; then
                echo "$loader_candidate"
                return 0
            fi
            return 1
            ;;
        @rpath/*)
            local name="${dep#@rpath/}"
            local rpath
            while IFS= read -r rpath; do
                [ -n "$rpath" ] || continue
                case "$rpath" in
                    @loader_path/*)
                        rpath="$origin_dir/${rpath#@loader_path/}"
                        ;;
                    @executable_path/*|@rpath/*)
                        continue
                        ;;
                esac
                if [ -f "$rpath/$name" ]; then
                    echo "$rpath/$name"
                    return 0
                fi
            done < <(otool -l "$origin" | awk '/cmd LC_RPATH/{c=1} c && $1=="path"{print $2; c=0}')
            if [ -f "$HOMEBREW_PREFIX/lib/$name" ]; then
                echo "$HOMEBREW_PREFIX/lib/$name"
                return 0
            fi
            return 1
            ;;
        "$HOMEBREW_PREFIX"/*)
            echo "$dep"
            ;;
        *)
            return 1
            ;;
    esac
}

bins=("$APP/Contents/MacOS/Spek")
origins=("$APP/Contents/MacOS/Spek")
i=0
while [ "$i" -lt "${#bins[@]}" ]; do
    bin="${bins[$i]}"
    origin="${origins[$i]}"
    echo "Updating dependendies for $bin."
    while IFS= read -r lib; do
        [ -n "$lib" ] || continue
        if ! resolved="$(resolve_dep "$lib" "$origin")"; then
            continue
        fi
        if [ ! -f "$resolved" ]; then
            echo "Missing dependency $lib (resolved $resolved)" >&2
            exit 1
        fi
        reallib="$(realpath "$resolved")"
        libname="$(basename "$reallib")"
        install_name_tool -change "$lib" "@executable_path/../Frameworks/$libname" "$bin"
        if [ ! -f "$APP/Contents/Frameworks/$libname" ]; then
            echo "	Bundling $reallib."
            cp "$reallib" "$APP/Contents/Frameworks/"
            chmod +w "$APP/Contents/Frameworks/$libname"
            install_name_tool -id "@executable_path/../Frameworks/$libname" "$APP/Contents/Frameworks/$libname"
            bins+=("$APP/Contents/Frameworks/$libname")
            origins+=("$reallib")
        fi
    done < <(otool -L "$bin" | awk '/^\t/ {print $1}')
    i=$((i + 1))
done

echo "Verifying bundled install names..."
shopt -s nullglob
bundled=("$APP/Contents/MacOS/Spek" "$APP"/Contents/Frameworks/*.dylib)
shopt -u nullglob
for f in "${bundled[@]}"; do
    while IFS= read -r lib; do
        [ -n "$lib" ] || continue
        case "$lib" in
            @executable_path/*|/usr/lib/*|/System/*)
                ;;
            *)
                echo "Unbundled dependency in $f: $lib" >&2
                exit 1
                ;;
        esac
    done < <(otool -L "$f" | awk '/^\t/ {print $1}')
done

# Ad-hoc sign. install_name_tool invalidates existing signatures.
# Still not notarized; Gatekeeper may require right-click Open.
shopt -s nullglob
for dylib in "$APP"/Contents/Frameworks/*; do
    codesign --force --sign - "$dylib"
done
shopt -u nullglob
codesign --force --deep --sign - "$APP"

mkdir -p "$OUT_DIR"
ZIP_NAME="spek-${VERSION}-macos-arm64.zip"
rm -f "$OUT_DIR/$ZIP_NAME"
echo "Creating $ZIP_NAME..."
ditto -c -k --keepParent "$APP" "$OUT_DIR/$ZIP_NAME"

echo "Done: $OUT_DIR/$ZIP_NAME"
